### ISSUE TITLE
Split Repos

### ISSUE THREAD

**Issue by RL-Lipsware** [Dr-PPSN/BBS-Projekt-Olympia#2]
Mono Repo macht auf dauer nur Probleme. Lieber Backend-Api Versionieren.

In Readme am besten denn aufs jeweilig anderen Repo verlinken

**Comment by Dr-PPSN** [comment]
Erstell erstmal eigene Repos und lad ein paar Projekte hoch bevor du den Leuten sagst wie man es richtig macht...
